# Weather Data Collection From Open Meteo

In [2]:
import requests
import pandas as pd

In [3]:
url = "https://archive-api.open-meteo.com/v1/archive"

params = {
	"latitude": 24.8608,
	"longitude": 67.0104,
	"start_date": "2024-08-01",
	"end_date": "2026-08-01",
	"hourly": ["temperature_2m", "wind_speed_10m", "relative_humidity_2m", "surface_pressure"],
	"timezone": "auto",
}

response = requests.get(url, params)

In [4]:
data = response.json()

In [5]:
weatherData = pd.DataFrame(data["hourly"])

In [6]:
weatherData.head()

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure
0,2024-08-01T00:00,28.7,23.3,88,998.8
1,2024-08-01T01:00,28.6,22.4,88,998.2
2,2024-08-01T02:00,28.6,22.6,87,997.8
3,2024-08-01T03:00,28.7,23.9,85,997.5
4,2024-08-01T04:00,28.6,24.4,85,997.8

In [7]:
weatherData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  17544 non-null  object
 1   temperature_2m        17544 non-null  float64
 2   wind_speed_10m        17544 non-null  float64
 3   relative_humidity_2m  17544 non-null  int64
 4   surface_pressure      17544 non-null  float64
dtypes: float64(3), int64(1), object(1)
memory usage: 685.4+ KB

In [8]:
weatherData.time = pd.to_datetime(weatherData.time)

In [9]:
weatherData.time = weatherData.time.dt.tz_localize('Asia/Karachi')

In [10]:
weatherData.head()

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure
0,2024-08-01 00:00:00+05:00,28.7,23.3,88,998.8
1,2024-08-01 01:00:00+05:00,28.6,22.4,88,998.2
2,2024-08-01 02:00:00+05:00,28.6,22.6,87,997.8
3,2024-08-01 03:00:00+05:00,28.7,23.9,85,997.5
4,2024-08-01 04:00:00+05:00,28.6,24.4,85,997.8

In [11]:
weatherData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  17544 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        17544 non-null  float64
 2   wind_speed_10m        17544 non-null  float64
 3   relative_humidity_2m  17544 non-null  int64
 4   surface_pressure      17544 non-null  float64
dtypes: datetime64[ns, Asia/Karachi](1), float64(3), int64(1)
memory usage: 685.4 KB

# AQI Data Collection from Open Meteo

In [12]:
url2 = "https://air-quality-api.open-meteo.com/v1/air-quality"

params2 = {
	"latitude": 24.8608,
	"longitude": 67.0104,
	"hourly": ["pm10", "pm2_5", "carbon_monoxide", "nitrogen_dioxide", "sulphur_dioxide", "ozone", "us_aqi"],
	"timezone": "auto",
	"start_date": "2024-08-01",
	"end_date": "2026-08-01",
}

response2 = requests.get(url2, params2)

In [13]:
data2 = response2.json()

In [14]:
aqiData = pd.DataFrame(data2["hourly"])

In [15]:
aqiData.head()

,time,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi
0,2024-08-01T00:00,46.8,20.5,217.0,14.6,4.6,43.0,66
1,2024-08-01T01:00,46.0,18.9,180.0,10.5,4.0,45.0,66
2,2024-08-01T02:00,46.4,17.9,152.0,7.4,3.6,47.0,66
3,2024-08-01T03:00,47.1,17.2,136.0,5.8,3.4,48.0,66
4,2024-08-01T04:00,47.1,16.9,128.0,5.1,3.5,48.0,66

In [16]:
aqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   time              17544 non-null  object
 1   pm10              17544 non-null  float64
 2   pm2_5             17544 non-null  float64
 3   carbon_monoxide   17544 non-null  float64
 4   nitrogen_dioxide  17544 non-null  float64
 5   sulphur_dioxide   17544 non-null  float64
 6   ozone             17544 non-null  float64
 7   us_aqi            17544 non-null  int64
dtypes: float64(6), int64(1), object(1)
memory usage: 1.1+ MB

In [17]:
aqiData.time = pd.to_datetime(aqiData.time)

In [18]:
aqiData.time = aqiData.time.dt.tz_localize('Asia/Karachi')

In [19]:
aqiData.head()

,time,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi
0,2024-08-01 00:00:00+05:00,46.8,20.5,217.0,14.6,4.6,43.0,66
1,2024-08-01 01:00:00+05:00,46.0,18.9,180.0,10.5,4.0,45.0,66
2,2024-08-01 02:00:00+05:00,46.4,17.9,152.0,7.4,3.6,47.0,66
3,2024-08-01 03:00:00+05:00,47.1,17.2,136.0,5.8,3.4,48.0,66
4,2024-08-01 04:00:00+05:00,47.1,16.9,128.0,5.1,3.5,48.0,66

In [20]:
aqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   time              17544 non-null  datetime64[ns, Asia/Karachi]
 1   pm10              17544 non-null  float64
 2   pm2_5             17544 non-null  float64
 3   carbon_monoxide   17544 non-null  float64
 4   nitrogen_dioxide  17544 non-null  float64
 5   sulphur_dioxide   17544 non-null  float64
 6   ozone             17544 non-null  float64
 7   us_aqi            17544 non-null  int64
dtypes: datetime64[ns, Asia/Karachi](1), float64(6), int64(1)
memory usage: 1.1 MB

In [21]:
print(aqiData["time"].min())
print(aqiData["time"].max())
print(len(aqiData))

2024-08-01 00:00:00+05:00
2026-08-01 23:00:00+05:00
17544

# Merge The Weather And AQI Data

In [22]:
AqiData = pd.merge(weatherData, aqiData, on = 'time')

In [24]:
AqiData.head()

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi
0,2024-08-01 00:00:00+05:00,28.7,23.3,88,998.8,46.8,20.5,217.0,14.6,4.6,43.0,66
1,2024-08-01 01:00:00+05:00,28.6,22.4,88,998.2,46.0,18.9,180.0,10.5,4.0,45.0,66
2,2024-08-01 02:00:00+05:00,28.6,22.6,87,997.8,46.4,17.9,152.0,7.4,3.6,47.0,66
3,2024-08-01 03:00:00+05:00,28.7,23.9,85,997.5,47.1,17.2,136.0,5.8,3.4,48.0,66
4,2024-08-01 04:00:00+05:00,28.6,24.4,85,997.8,47.1,16.9,128.0,5.1,3.5,48.0,66

In [25]:
AqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  17544 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        17544 non-null  float64
 2   wind_speed_10m        17544 non-null  float64
 3   relative_humidity_2m  17544 non-null  int64
 4   surface_pressure      17544 non-null  float64
 5   pm10                  17544 non-null  float64
 6   pm2_5                 17544 non-null  float64
 7   carbon_monoxide       17544 non-null  float64
 8   nitrogen_dioxide      17544 non-null  float64
 9   sulphur_dioxide       17544 non-null  float64
 10  ozone                 17544 non-null  float64
 11  us_aqi                17544 non-null  int64
dtypes: datetime64[ns, Asia/Karachi](1), float64(9), int64(2)
memory usage: 1.6 MB

# Adding New Features

### Time Based Features

In [26]:
AqiData["Hour"] = AqiData["time"].dt.hour
AqiData["Day"] = AqiData["time"].dt.day
AqiData["Month"] = AqiData["time"].dt.month

### AQI Change Rate

In [28]:
AqiData["AQI Change Rate"] = AqiData["us_aqi"].diff()

In [32]:
AqiData.head(100)

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,Hour,Day,Month,AQI Change Rate
0,2024-08-01 00:00:00+05:00,28.7,23.3,88,998.8,46.8,20.5,217.0,14.6,4.6,43.0,66,0,1,8,0.0
1,2024-08-01 01:00:00+05:00,28.6,22.4,88,998.2,46.0,18.9,180.0,10.5,4.0,45.0,66,1,1,8,0.0
2,2024-08-01 02:00:00+05:00,28.6,22.6,87,997.8,46.4,17.9,152.0,7.4,3.6,47.0,66,2,1,8,0.0
3,2024-08-01 03:00:00+05:00,28.7,23.9,85,997.5,47.1,17.2,136.0,5.8,3.4,48.0,66,3,1,8,0.0
4,2024-08-01 04:00:00+05:00,28.6,24.4,85,997.8,47.1,16.9,128.0,5.1,3.5,48.0,66,4,1,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-08-04 23:00:00+05:00,27.9,12.5,86,998.6,135.0,33.6,302.0,25.3,6.1,26.0,97,23,4,8,0.0
96,2024-08-05 00:00:00+05:00,27.4,12.5,88,998.5,135.5,33.9,284.0,23.2,5.9,28.0,97,0,5,8,0.0
97,2024-08-05 01:00:00+05:00,27.1,12.9,89,998.3,134.1,33.8,261.0,20.4,5.6,30.0,97,1,5,8,0.0
98,2024-08-05 02:00:00+05:00,26.4,12.1,92,998.3,129.9,33.2,237.0,17.6,5.3,33.0,98,2,5,8,1.0
99,2024-08-05 03:00:00+05:00,26.8,9.4,90,998.0,122.5,32.0,210.0,14.9,5.2,35.0,98,3,5,8,0.0

In [30]:
AqiData["AQI Change Rate"] = AqiData["AQI Change Rate"].fillna(0)

In [31]:
AqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  17544 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        17544 non-null  float64
 2   wind_speed_10m        17544 non-null  float64
 3   relative_humidity_2m  17544 non-null  int64
 4   surface_pressure      17544 non-null  float64
 5   pm10                  17544 non-null  float64
 6   pm2_5                 17544 non-null  float64
 7   carbon_monoxide       17544 non-null  float64
 8   nitrogen_dioxide      17544 non-null  float64
 9   sulphur_dioxide       17544 non-null  float64
 10  ozone                 17544 non-null  float64
 11  us_aqi                17544 non-null  int64
 12  Hour                  17544 non-null  int32
 13  Day                   17544 non-null  int32
 14  Month                 17544 non-null  int32
 15  AQI Change Rate       17544 non-null  float64
dtypes: datetime64[ns, Asia/Karachi](1), float64(10), int32(3), int64(2)
memory usage: 1.9 MB

In [33]:
AqiData.to_csv("AqiData.csv")