# Weather Data Collection From Open Meteo

In [49]:
import requests
import pandas as pd

In [50]:
url = "https://archive-api.open-meteo.com/v1/archive"

params = {
	"latitude": 24.8608,
	"longitude": 67.0104,
	"start_date": "2023-08-01",
	"end_date": "2026-08-01",
	"hourly": ["temperature_2m", "wind_speed_10m", "relative_humidity_2m", "surface_pressure"],
	"timezone": "auto",
}

response = requests.get(url, params)

In [51]:
data = response.json()

In [52]:
weatherData = pd.DataFrame(data["hourly"])

In [53]:
weatherData.head()

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure
0,2023-08-01T00:00,27.5,22.2,90,1000.4
1,2023-08-01T01:00,27.5,22.2,90,999.9
2,2023-08-01T02:00,27.4,20.8,91,999.4
3,2023-08-01T03:00,27.5,19.2,91,999.4
4,2023-08-01T04:00,27.2,19.1,92,999.3

In [54]:
weatherData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26328 non-null  object
 1   temperature_2m        26328 non-null  float64
 2   wind_speed_10m        26328 non-null  float64
 3   relative_humidity_2m  26328 non-null  int64
 4   surface_pressure      26328 non-null  float64
dtypes: float64(3), int64(1), object(1)
memory usage: 1.0+ MB

In [55]:
weatherData.time = pd.to_datetime(weatherData.time)

In [56]:
weatherData.time = weatherData.time.dt.tz_localize('Asia/Karachi')

In [57]:
weatherData.head()

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure
0,2023-08-01 00:00:00+05:00,27.5,22.2,90,1000.4
1,2023-08-01 01:00:00+05:00,27.5,22.2,90,999.9
2,2023-08-01 02:00:00+05:00,27.4,20.8,91,999.4
3,2023-08-01 03:00:00+05:00,27.5,19.2,91,999.4
4,2023-08-01 04:00:00+05:00,27.2,19.1,92,999.3

In [58]:
weatherData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26328 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        26328 non-null  float64
 2   wind_speed_10m        26328 non-null  float64
 3   relative_humidity_2m  26328 non-null  int64
 4   surface_pressure      26328 non-null  float64
dtypes: datetime64[ns, Asia/Karachi](1), float64(3), int64(1)
memory usage: 1.0 MB

# AQI Data Collection from Open Meteo

In [59]:
url2 = "https://air-quality-api.open-meteo.com/v1/air-quality"

params2 = {
	"latitude": 24.8608,
	"longitude": 67.0104,
	"hourly": ["pm10", "pm2_5", "carbon_monoxide", "nitrogen_dioxide", "sulphur_dioxide", "ozone", "us_aqi"],
	"timezone": "auto",
	"start_date": "2023-08-01",
	"end_date": "2026-08-01",
}

response2 = requests.get(url2, params2)

In [60]:
data2 = response2.json()

In [61]:
aqiData = pd.DataFrame(data2["hourly"])

In [62]:
aqiData.head()

,time,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi
0,2023-08-01T00:00,61.9,20.8,174.0,12.3,3.9,33.0,73
1,2023-08-01T01:00,62.4,19.7,150.0,9.5,3.6,35.0,73
2,2023-08-01T02:00,67.1,19.6,131.0,7.3,3.3,37.0,73
3,2023-08-01T03:00,72.6,19.8,117.0,5.9,3.2,38.0,73
4,2023-08-01T04:00,75.2,20.4,107.0,5.2,3.2,39.0,73

In [63]:
aqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   time              26328 non-null  object
 1   pm10              26328 non-null  float64
 2   pm2_5             26328 non-null  float64
 3   carbon_monoxide   26328 non-null  float64
 4   nitrogen_dioxide  26328 non-null  float64
 5   sulphur_dioxide   26328 non-null  float64
 6   ozone             26328 non-null  float64
 7   us_aqi            26328 non-null  int64
dtypes: float64(6), int64(1), object(1)
memory usage: 1.6+ MB

In [64]:
aqiData.time = pd.to_datetime(aqiData.time)

In [65]:
aqiData.time = aqiData.time.dt.tz_localize('Asia/Karachi')

In [66]:
aqiData.head()

,time,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi
0,2023-08-01 00:00:00+05:00,61.9,20.8,174.0,12.3,3.9,33.0,73
1,2023-08-01 01:00:00+05:00,62.4,19.7,150.0,9.5,3.6,35.0,73
2,2023-08-01 02:00:00+05:00,67.1,19.6,131.0,7.3,3.3,37.0,73
3,2023-08-01 03:00:00+05:00,72.6,19.8,117.0,5.9,3.2,38.0,73
4,2023-08-01 04:00:00+05:00,75.2,20.4,107.0,5.2,3.2,39.0,73

In [67]:
aqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   time              26328 non-null  datetime64[ns, Asia/Karachi]
 1   pm10              26328 non-null  float64
 2   pm2_5             26328 non-null  float64
 3   carbon_monoxide   26328 non-null  float64
 4   nitrogen_dioxide  26328 non-null  float64
 5   sulphur_dioxide   26328 non-null  float64
 6   ozone             26328 non-null  float64
 7   us_aqi            26328 non-null  int64
dtypes: datetime64[ns, Asia/Karachi](1), float64(6), int64(1)
memory usage: 1.6 MB

In [68]:
print(aqiData["time"].min())
print(aqiData["time"].max())
print(len(aqiData))

2023-08-01 00:00:00+05:00
2026-08-01 23:00:00+05:00
26328

# Merge The Weather And AQI Data

In [69]:
AqiData = pd.merge(weatherData, aqiData, on = 'time')

In [70]:
AqiData.head()

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi
0,2023-08-01 00:00:00+05:00,27.5,22.2,90,1000.4,61.9,20.8,174.0,12.3,3.9,33.0,73
1,2023-08-01 01:00:00+05:00,27.5,22.2,90,999.9,62.4,19.7,150.0,9.5,3.6,35.0,73
2,2023-08-01 02:00:00+05:00,27.4,20.8,91,999.4,67.1,19.6,131.0,7.3,3.3,37.0,73
3,2023-08-01 03:00:00+05:00,27.5,19.2,91,999.4,72.6,19.8,117.0,5.9,3.2,38.0,73
4,2023-08-01 04:00:00+05:00,27.2,19.1,92,999.3,75.2,20.4,107.0,5.2,3.2,39.0,73

In [71]:
AqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26328 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        26328 non-null  float64
 2   wind_speed_10m        26328 non-null  float64
 3   relative_humidity_2m  26328 non-null  int64
 4   surface_pressure      26328 non-null  float64
 5   pm10                  26328 non-null  float64
 6   pm2_5                 26328 non-null  float64
 7   carbon_monoxide       26328 non-null  float64
 8   nitrogen_dioxide      26328 non-null  float64
 9   sulphur_dioxide       26328 non-null  float64
 10  ozone                 26328 non-null  float64
 11  us_aqi                26328 non-null  int64
dtypes: datetime64[ns, Asia/Karachi](1), float64(9), int64(2)
memory usage: 2.4 MB

In [72]:
AqiData.to_csv("AqiDataKarachi.csv")