# Weather Data Collection From Open Meteo

In [33]:
import requests
import pandas as pd

In [34]:
url = "https://archive-api.open-meteo.com/v1/archive"

params = {
	"latitude": 24.8608,
	"longitude": 67.0104,
	"start_date": "2023-08-01",
	"end_date": "2026-08-01",
	"hourly": ["temperature_2m", "wind_speed_10m", "relative_humidity_2m", "surface_pressure"],
	"timezone": "auto",
}

response = requests.get(url, params)

In [35]:
data = response.json()

In [36]:
weatherData = pd.DataFrame(data["hourly"])

In [37]:
weatherData.head()

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure
0,2023-08-01T00:00,27.5,22.2,90,1000.4
1,2023-08-01T01:00,27.5,22.2,90,999.9
2,2023-08-01T02:00,27.4,20.8,91,999.4
3,2023-08-01T03:00,27.5,19.2,91,999.4
4,2023-08-01T04:00,27.2,19.1,92,999.3

In [38]:
weatherData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26328 non-null  object
 1   temperature_2m        26328 non-null  float64
 2   wind_speed_10m        26328 non-null  float64
 3   relative_humidity_2m  26328 non-null  int64
 4   surface_pressure      26328 non-null  float64
dtypes: float64(3), int64(1), object(1)
memory usage: 1.0+ MB

In [39]:
weatherData.time = pd.to_datetime(weatherData.time)

In [40]:
weatherData.time = weatherData.time.dt.tz_localize('Asia/Karachi')

In [41]:
weatherData.head()

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure
0,2023-08-01 00:00:00+05:00,27.5,22.2,90,1000.4
1,2023-08-01 01:00:00+05:00,27.5,22.2,90,999.9
2,2023-08-01 02:00:00+05:00,27.4,20.8,91,999.4
3,2023-08-01 03:00:00+05:00,27.5,19.2,91,999.4
4,2023-08-01 04:00:00+05:00,27.2,19.1,92,999.3

In [42]:
weatherData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26328 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        26328 non-null  float64
 2   wind_speed_10m        26328 non-null  float64
 3   relative_humidity_2m  26328 non-null  int64
 4   surface_pressure      26328 non-null  float64
dtypes: datetime64[ns, Asia/Karachi](1), float64(3), int64(1)
memory usage: 1.0 MB

# AQI Data Collection from Open Meteo

In [43]:
url2 = "https://air-quality-api.open-meteo.com/v1/air-quality"

params2 = {
	"latitude": 24.8608,
	"longitude": 67.0104,
	"hourly": ["pm10", "pm2_5", "carbon_monoxide", "nitrogen_dioxide", "sulphur_dioxide", "ozone", "us_aqi"],
	"timezone": "auto",
	"start_date": "2023-08-01",
	"end_date": "2026-08-01",
}

response2 = requests.get(url2, params2)

In [44]:
data2 = response2.json()

In [45]:
aqiData = pd.DataFrame(data2["hourly"])

In [46]:
aqiData.head()

,time,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi
0,2023-08-01T00:00,61.9,20.8,174.0,12.3,3.9,33.0,73
1,2023-08-01T01:00,62.4,19.7,150.0,9.5,3.6,35.0,73
2,2023-08-01T02:00,67.1,19.6,131.0,7.3,3.3,37.0,73
3,2023-08-01T03:00,72.6,19.8,117.0,5.9,3.2,38.0,73
4,2023-08-01T04:00,75.2,20.4,107.0,5.2,3.2,39.0,73

In [47]:
aqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   time              26328 non-null  object
 1   pm10              26328 non-null  float64
 2   pm2_5             26328 non-null  float64
 3   carbon_monoxide   26328 non-null  float64
 4   nitrogen_dioxide  26328 non-null  float64
 5   sulphur_dioxide   26328 non-null  float64
 6   ozone             26328 non-null  float64
 7   us_aqi            26328 non-null  int64
dtypes: float64(6), int64(1), object(1)
memory usage: 1.6+ MB

In [48]:
aqiData.time = pd.to_datetime(aqiData.time)

In [49]:
aqiData.time = aqiData.time.dt.tz_localize('Asia/Karachi')

In [50]:
aqiData.head()

,time,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi
0,2023-08-01 00:00:00+05:00,61.9,20.8,174.0,12.3,3.9,33.0,73
1,2023-08-01 01:00:00+05:00,62.4,19.7,150.0,9.5,3.6,35.0,73
2,2023-08-01 02:00:00+05:00,67.1,19.6,131.0,7.3,3.3,37.0,73
3,2023-08-01 03:00:00+05:00,72.6,19.8,117.0,5.9,3.2,38.0,73
4,2023-08-01 04:00:00+05:00,75.2,20.4,107.0,5.2,3.2,39.0,73

In [51]:
aqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   time              26328 non-null  datetime64[ns, Asia/Karachi]
 1   pm10              26328 non-null  float64
 2   pm2_5             26328 non-null  float64
 3   carbon_monoxide   26328 non-null  float64
 4   nitrogen_dioxide  26328 non-null  float64
 5   sulphur_dioxide   26328 non-null  float64
 6   ozone             26328 non-null  float64
 7   us_aqi            26328 non-null  int64
dtypes: datetime64[ns, Asia/Karachi](1), float64(6), int64(1)
memory usage: 1.6 MB

In [52]:
print(aqiData["time"].min())
print(aqiData["time"].max())
print(len(aqiData))

2023-08-01 00:00:00+05:00
2026-08-01 23:00:00+05:00
26328

# Merge The Weather And AQI Data

In [53]:
AqiData = pd.merge(weatherData, aqiData, on = 'time')

In [54]:
AqiData.head()

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi
0,2023-08-01 00:00:00+05:00,27.5,22.2,90,1000.4,61.9,20.8,174.0,12.3,3.9,33.0,73
1,2023-08-01 01:00:00+05:00,27.5,22.2,90,999.9,62.4,19.7,150.0,9.5,3.6,35.0,73
2,2023-08-01 02:00:00+05:00,27.4,20.8,91,999.4,67.1,19.6,131.0,7.3,3.3,37.0,73
3,2023-08-01 03:00:00+05:00,27.5,19.2,91,999.4,72.6,19.8,117.0,5.9,3.2,38.0,73
4,2023-08-01 04:00:00+05:00,27.2,19.1,92,999.3,75.2,20.4,107.0,5.2,3.2,39.0,73

In [55]:
AqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26328 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        26328 non-null  float64
 2   wind_speed_10m        26328 non-null  float64
 3   relative_humidity_2m  26328 non-null  int64
 4   surface_pressure      26328 non-null  float64
 5   pm10                  26328 non-null  float64
 6   pm2_5                 26328 non-null  float64
 7   carbon_monoxide       26328 non-null  float64
 8   nitrogen_dioxide      26328 non-null  float64
 9   sulphur_dioxide       26328 non-null  float64
 10  ozone                 26328 non-null  float64
 11  us_aqi                26328 non-null  int64
dtypes: datetime64[ns, Asia/Karachi](1), float64(9), int64(2)
memory usage: 2.4 MB

# Adding New Features

### Time Based Features

In [56]:
AqiData["Hour"] = AqiData["time"].dt.hour
AqiData["Day"] = AqiData["time"].dt.day
AqiData["Month"] = AqiData["time"].dt.month

In [57]:
AqiData.head()

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,Hour,Day,Month
0,2023-08-01 00:00:00+05:00,27.5,22.2,90,1000.4,61.9,20.8,174.0,12.3,3.9,33.0,73,0,1,8
1,2023-08-01 01:00:00+05:00,27.5,22.2,90,999.9,62.4,19.7,150.0,9.5,3.6,35.0,73,1,1,8
2,2023-08-01 02:00:00+05:00,27.4,20.8,91,999.4,67.1,19.6,131.0,7.3,3.3,37.0,73,2,1,8
3,2023-08-01 03:00:00+05:00,27.5,19.2,91,999.4,72.6,19.8,117.0,5.9,3.2,38.0,73,3,1,8
4,2023-08-01 04:00:00+05:00,27.2,19.1,92,999.3,75.2,20.4,107.0,5.2,3.2,39.0,73,4,1,8

# AQI Current hour karachi

In [58]:
AqiData.to_csv("AqiDataHourKarachi.csv")

### AQI Change Rate

In [59]:
AqiData["AQI Change Rate"] = AqiData["us_aqi"].diff()

In [60]:
AqiData.head(100)

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,Hour,Day,Month,AQI Change Rate
0,2023-08-01 00:00:00+05:00,27.5,22.2,90,1000.4,61.9,20.8,174.0,12.3,3.9,33.0,73,0,1,8,NaN
1,2023-08-01 01:00:00+05:00,27.5,22.2,90,999.9,62.4,19.7,150.0,9.5,3.6,35.0,73,1,1,8,0.0
2,2023-08-01 02:00:00+05:00,27.4,20.8,91,999.4,67.1,19.6,131.0,7.3,3.3,37.0,73,2,1,8,0.0
3,2023-08-01 03:00:00+05:00,27.5,19.2,91,999.4,72.6,19.8,117.0,5.9,3.2,38.0,73,3,1,8,0.0
4,2023-08-01 04:00:00+05:00,27.2,19.1,92,999.3,75.2,20.4,107.0,5.2,3.2,39.0,73,4,1,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-08-04 23:00:00+05:00,27.3,14.4,88,1002.5,90.6,23.5,192.0,13.1,4.5,42.0,84,23,4,8,0.0
96,2023-08-05 00:00:00+05:00,27.3,14.1,88,1002.2,93.4,23.4,174.0,11.2,4.2,44.0,83,0,5,8,-1.0
97,2023-08-05 01:00:00+05:00,27.1,14.2,89,1002.1,90.3,22.2,150.0,8.6,3.8,46.0,83,1,5,8,0.0
98,2023-08-05 02:00:00+05:00,27.0,16.9,90,1001.6,97.6,22.9,131.0,6.6,3.5,48.0,83,2,5,8,0.0
99,2023-08-05 03:00:00+05:00,26.9,19.4,91,1001.2,104.1,24.4,119.0,5.7,3.5,48.0,83,3,5,8,0.0

In [61]:
AqiData["AQI Change Rate"] = AqiData["AQI Change Rate"].fillna(0)

In [62]:
AqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26328 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        26328 non-null  float64
 2   wind_speed_10m        26328 non-null  float64
 3   relative_humidity_2m  26328 non-null  int64
 4   surface_pressure      26328 non-null  float64
 5   pm10                  26328 non-null  float64
 6   pm2_5                 26328 non-null  float64
 7   carbon_monoxide       26328 non-null  float64
 8   nitrogen_dioxide      26328 non-null  float64
 9   sulphur_dioxide       26328 non-null  float64
 10  ozone                 26328 non-null  float64
 11  us_aqi                26328 non-null  int64
 12  Hour                  26328 non-null  int32
 13  Day                   26328 non-null  int32
 14  Month                 26328 non-null  int32
 15  AQI Change Rate       26328 non-null  float64
dtypes: datetime64[ns, Asia/Karachi](1), float64(10), int32(3), int64(2)
memory usage: 2.9 MB

In [63]:
AqiData.to_csv("AqiDataHourChangeRateKarachi.csv")

# 1 Day Prediction Aqi

In [64]:
AqiData["1 Day Future Aqi"] = AqiData['us_aqi'].shift(-24)

In [65]:
AqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26328 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        26328 non-null  float64
 2   wind_speed_10m        26328 non-null  float64
 3   relative_humidity_2m  26328 non-null  int64
 4   surface_pressure      26328 non-null  float64
 5   pm10                  26328 non-null  float64
 6   pm2_5                 26328 non-null  float64
 7   carbon_monoxide       26328 non-null  float64
 8   nitrogen_dioxide      26328 non-null  float64
 9   sulphur_dioxide       26328 non-null  float64
 10  ozone                 26328 non-null  float64
 11  us_aqi                26328 non-null  int64
 12  Hour                  26328 non-null  int32
 13  Day                   26328 non-null  int32
 14  Month                 26328 non-null  int32
 15  AQI Change Rate       26328 non-null  float64
 16  1 Day Future Aqi      26304 non-null  float64
dtypes: datetime64[ns, Asia/Karachi](1), float64(11), int32(3), int64(2)
memory usage: 3.1 MB

In [66]:
AqiData_One_Day = AqiData.dropna()

In [67]:
AqiData_One_Day.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26304 entries, 0 to 26303
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26304 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        26304 non-null  float64
 2   wind_speed_10m        26304 non-null  float64
 3   relative_humidity_2m  26304 non-null  int64
 4   surface_pressure      26304 non-null  float64
 5   pm10                  26304 non-null  float64
 6   pm2_5                 26304 non-null  float64
 7   carbon_monoxide       26304 non-null  float64
 8   nitrogen_dioxide      26304 non-null  float64
 9   sulphur_dioxide       26304 non-null  float64
 10  ozone                 26304 non-null  float64
 11  us_aqi                26304 non-null  int64
 12  Hour                  26304 non-null  int32
 13  Day                   26304 non-null  int32
 14  Month                 26304 non-null  int32
 15  AQI Change Rate       26304 non-null  float64
 16  1 Day Future Aqi      26304 non-null  float64
dtypes: datetime64[ns, Asia/Karachi](1), float64(11), int32(3), int64(2)
memory usage: 3.3 MB

In [69]:
AqiData_One_Day.to_csv("AqiData1DayPrediction.csv")

# 2 Day Prediction Aqi

In [70]:
AqiData["2 Day Future Aqi"] = AqiData['us_aqi'].shift(-48)

In [71]:
AqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26328 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        26328 non-null  float64
 2   wind_speed_10m        26328 non-null  float64
 3   relative_humidity_2m  26328 non-null  int64
 4   surface_pressure      26328 non-null  float64
 5   pm10                  26328 non-null  float64
 6   pm2_5                 26328 non-null  float64
 7   carbon_monoxide       26328 non-null  float64
 8   nitrogen_dioxide      26328 non-null  float64
 9   sulphur_dioxide       26328 non-null  float64
 10  ozone                 26328 non-null  float64
 11  us_aqi                26328 non-null  int64
 12  Hour                  26328 non-null  int32
 13  Day                   26328 non-null  int32
 14  Month                 26328 non-null  int32
 15  AQI Change Rate       26328 non-null  float64
 16  1 Day Future Aqi      26304 non-null  float64
 17  2 Day Future Aqi      26280 non-null  float64
dtypes: datetime64[ns, Asia/Karachi](1), float64(12), int32(3), int64(2)
memory usage: 3.3 MB

In [73]:
AqiData_Two_Day = AqiData.dropna()

In [74]:
AqiData_Two_Day.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26280 entries, 0 to 26279
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26280 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        26280 non-null  float64
 2   wind_speed_10m        26280 non-null  float64
 3   relative_humidity_2m  26280 non-null  int64
 4   surface_pressure      26280 non-null  float64
 5   pm10                  26280 non-null  float64
 6   pm2_5                 26280 non-null  float64
 7   carbon_monoxide       26280 non-null  float64
 8   nitrogen_dioxide      26280 non-null  float64
 9   sulphur_dioxide       26280 non-null  float64
 10  ozone                 26280 non-null  float64
 11  us_aqi                26280 non-null  int64
 12  Hour                  26280 non-null  int32
 13  Day                   26280 non-null  int32
 14  Month                 26280 non-null  int32
 15  AQI Change Rate       26280 non-null  float64
 16  1 Day Future Aqi      26280 non-null  float64
 17  2 Day Future Aqi      26280 non-null  float64
dtypes: datetime64[ns, Asia/Karachi](1), float64(12), int32(3), int64(2)
memory usage: 3.5 MB

In [75]:
AqiData_Two_Day.to_csv("AqiData2DayPrediction.csv")

# 3 Day Prediction Aqi

In [76]:
AqiData["3 Day Future Aqi"] = AqiData['us_aqi'].shift(-72)

In [77]:
AqiData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26328 entries, 0 to 26327
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26328 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        26328 non-null  float64
 2   wind_speed_10m        26328 non-null  float64
 3   relative_humidity_2m  26328 non-null  int64
 4   surface_pressure      26328 non-null  float64
 5   pm10                  26328 non-null  float64
 6   pm2_5                 26328 non-null  float64
 7   carbon_monoxide       26328 non-null  float64
 8   nitrogen_dioxide      26328 non-null  float64
 9   sulphur_dioxide       26328 non-null  float64
 10  ozone                 26328 non-null  float64
 11  us_aqi                26328 non-null  int64
 12  Hour                  26328 non-null  int32
 13  Day                   26328 non-null  int32
 14  Month                 26328 non-null  int32
 15  AQI Change Rate       26328 non-null  float64
 16  1 Day Future Aqi      26304 non-null  float64
 17  2 Day Future Aqi      26280 non-null  float64
 18  3 Day Future Aqi      26256 non-null  float64
dtypes: datetime64[ns, Asia/Karachi](1), float64(13), int32(3), int64(2)
memory usage: 3.5 MB

In [78]:
AqiData_Three_Day = AqiData.dropna()

In [79]:
AqiData_Three_Day.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26256 entries, 0 to 26255
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  26256 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        26256 non-null  float64
 2   wind_speed_10m        26256 non-null  float64
 3   relative_humidity_2m  26256 non-null  int64
 4   surface_pressure      26256 non-null  float64
 5   pm10                  26256 non-null  float64
 6   pm2_5                 26256 non-null  float64
 7   carbon_monoxide       26256 non-null  float64
 8   nitrogen_dioxide      26256 non-null  float64
 9   sulphur_dioxide       26256 non-null  float64
 10  ozone                 26256 non-null  float64
 11  us_aqi                26256 non-null  int64
 12  Hour                  26256 non-null  int32
 13  Day                   26256 non-null  int32
 14  Month                 26256 non-null  int32
 15  AQI Change Rate       26256 non-null  float64
 16  1 Day Future Aqi      26256 non-null  float64
 17  2 Day Future Aqi      26256 non-null  float64
 18  3 Day Future Aqi      26256 non-null  float64
dtypes: datetime64[ns, Asia/Karachi](1), float64(13), int32(3), int64(2)
memory usage: 3.7 MB

In [80]:
AqiData_Three_Day.to_csv("AqiData3DayPrediction.csv")